# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('source', models.SmallIntegerField()),
                ('picture', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-updated_at'],
                'db_table': 'house',
            },
        ),
    ]
